language: python

python: 3.7

env:
  - export GOOGLE_APPLICATION_CREDENTIALS="./serviceAccount.json"

before_install:
  - openssl aes-256-cbc -K $encrypted_6f0cce282614_key -iv $encrypted_6f0cce282614_iv -in serviceAccount.json.enc -out ./serviceAccount.json -d

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install flask_restplus
  - pip install flask
  - pip install werkzeug
  - pip install google-cloud-storage
  - pip install firebase_admin
  - pip install pandas


script:
  - python --version
  - pytest --cov=api tests/ --ignore tests/test_stress.py